### ISSUE TITLE
where is paper?

### ISSUE THREAD

**Issue by Romatic-zbj** [zwy0913/MFFT#1]
I am so excited to meet the MFIF with Transformer, but I can't find the paper on Google Scholar (Multi-focus image fusion via interactive transformer and asymmetric soft sharing). Could you share it in the repository?

**Comment by zwy0913** [comment]
Glad to have your interest in our work! Unfortunately, the paper is submitted and currently under review. This repository is only a demo for reviewers. We are so sorry that the paper is not available right now. Repository will be updated in time when progress.

**Comment by xiangxiang-wang** [comment]
你好，请问如何引用您这篇文章，想用来做对比方法？
