### ISSUE TITLE
How to cite your article？

### ISSUE THREAD

**Issue by xiangxiang-wang** [zwy0913/MFFT#2]
你好，请问如何引用您这篇文章，想用来做对比方法？

**Comment by zwy0913** [comment]
文章已投，目前在审，还未正式发表，欲引用请关注后续进展。这份代码是供审稿人参考的demo，我们将在正式发表后更新并完善这个仓库

**Comment by xiangxiang-wang** [comment]
好的，谢谢您的回复，后续会继续关注该项目。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Aug 29, 2023 02:36 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"xiangxiang ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [zwy0913/MFFT] How to cite your article？ (Issue #2)

&nbsp;



 
文章已投，目前在审，还未正式发表，欲引用请关注后续进展。这份代码是供审稿人参考的demo，我们将在正式发表后更新并完善这个仓库
